language: python

python:
- 3.6
- nightly

dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: kemus-github
    token:
      secure: amcBaCpYTT6nc1jwoffN03DOT0ueZ0txitj/9IA+SiHeq/xbBPGWpxdBk+XPanxV+Y+0dHHoY5m5M7oTYELsADZcFHOskVE7lREPhYR6DibCUa9vRNDO1E/e/LT/lNPJgJ846bkwbGtgLu+XGXKuqUlF6x6xvgM/DyHd/qv+TMb7wLyxA2D9YQpjg3HQVbaHNKP3Vvt5sBgnL3ZxSatjJyEaNEP0zgJIWAj3B6AsQHyDfCeODA5vxUByR4QsaDPrxekMerwheSDlXAGVb7ChOGmuLF13Q3OSMWTHW2gD+xYK4NE7vcOXEf0Cs4Ylj4oXYPWnEcVTZii0fgwNYz3c4NfboQfhTfiOePFedtTEz7Da90x4qwR8PiRCHVkCXy54V7y5p9kTZPLMyO6KSLcO0YZXOsy79xeuJkGGXqgqjWtlfQfZbiGvbDx2lpyiQC9musgTLvwOug3OQ1OZLCEIRVnvclVMYcHrAOP4oylUwMTbDUPT1BPeLFqhaGmhEKQXAsvmlPsjDR6aTfeqL0kOjQmBkHCWkmoG+9pLDmt88GLpjVXf23q7FjZccVLuSfUP1I+x12D1DOue8DtfX47q6YOuQ1bwIj7tT5N51A0Zm45O2RNYkiJb+TD9Qo/e0s7qt6A31MQ4mXMCPN0q/efELcGu7OkXYPikVTAga1n+Eeo=

jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.sonar/cache'

script:
  - sonar-scanner
  - pytest

